// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Config {
    "version": number;
    "targetDate": string;
    "countdownMode": string;
    "restWeekdays": number[] | null;
    "includeToday": boolean;
    "includeTargetDate": boolean;
    "petScale": number;
    "activityArea": string;
    "bottomMargin": number;
    "sleepDurationSeconds": number;
    "alwaysOnTop": boolean;
    "launchAtStartup": boolean;
    "bubbleEnabled": boolean;
    "bubbleIntervalMin": number;
    "bubbleIntervalMax": number;
    "bubbleDisplaySeconds": number;
    "bubbleCategories": { [_ in string]?: boolean } | null;
    "quietHours": QuietHours;
    "healthReminders": HealthReminders;
    "position": Position;
}

export interface HealthReminders {
    "enabled": boolean;
    "waterEnabled": boolean;
    "waterIntervalMinutes": number;
    "standEnabled": boolean;
    "standIntervalMinutes": number;
    "snoozeMinutes": number;
}

export interface Position {
    "displayId": string;
    "x": number;
    "y": number;
}

export interface QuietHours {
    "enabled": boolean;
    "start": string;
    "end": string;
}
