// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("targetDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetDate"] = "";
        }
        if (!("countdownMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["countdownMode"] = "";
        }
        if (!("restWeekdays" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["restWeekdays"] = [];
        }
        if (!("includeToday" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["includeToday"] = false;
        }
        if (!("includeTargetDate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["includeTargetDate"] = false;
        }
        if (!("petScale" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["petScale"] = 0;
        }
        if (!("activityArea" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activityArea"] = "";
        }
        if (!("bottomMargin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bottomMargin"] = 0;
        }
        if (!("sleepDurationSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sleepDurationSeconds"] = 0;
        }
        if (!("alwaysOnTop" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["alwaysOnTop"] = false;
        }
        if (!("launchAtStartup" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["launchAtStartup"] = false;
        }
        if (!("bubbleEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["bubbleEnabled"] = false;
        }
        if (!("bubbleIntervalMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bubbleIntervalMin"] = 0;
        }
        if (!("bubbleIntervalMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bubbleIntervalMax"] = 0;
        }
        if (!("bubbleDisplaySeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bubbleDisplaySeconds"] = 0;
        }
        if (!("bubbleCategories" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: boolean }}
             */
            this["bubbleCategories"] = {};
        }
        if (!("quietHours" in $$source)) {
            /**
             * @member
             * @type {QuietHours}
             */
            this["quietHours"] = (new QuietHours());
        }
        if (!("position" in $$source)) {
            /**
             * @member
             * @type {Position}
             */
            this["position"] = (new Position());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField16_0 = $$createType1;
        const $$createField17_0 = $$createType2;
        const $$createField18_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("restWeekdays" in $$parsedSource) {
            $$parsedSource["restWeekdays"] = $$createField3_0($$parsedSource["restWeekdays"]);
        }
        if ("bubbleCategories" in $$parsedSource) {
            $$parsedSource["bubbleCategories"] = $$createField16_0($$parsedSource["bubbleCategories"]);
        }
        if ("quietHours" in $$parsedSource) {
            $$parsedSource["quietHours"] = $$createField17_0($$parsedSource["quietHours"]);
        }
        if ("position" in $$parsedSource) {
            $$parsedSource["position"] = $$createField18_0($$parsedSource["position"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class Position {
    /**
     * Creates a new Position instance.
     * @param {Partial<Position>} [$$source = {}] - The source object to create the Position.
     */
    constructor($$source = {}) {
        if (!("displayId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayId"] = "";
        }
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Position instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Position}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Position(/** @type {Partial<Position>} */($$parsedSource));
    }
}

export class QuietHours {
    /**
     * Creates a new QuietHours instance.
     * @param {Partial<QuietHours>} [$$source = {}] - The source object to create the QuietHours.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("start" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["start"] = "";
        }
        if (!("end" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["end"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuietHours instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QuietHours}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuietHours(/** @type {Partial<QuietHours>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = QuietHours.createFrom;
const $$createType3 = Position.createFrom;
