// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Result {
    /**
     * Creates a new Result instance.
     * @param {Partial<Result>} [$$source = {}] - The source object to create the Result.
     */
    constructor($$source = {}) {
        if (!("targetDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetDate"] = "";
        }
        if (!("calendarDays" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["calendarDays"] = 0;
        }
        if (!("workingDays" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["workingDays"] = 0;
        }
        if (!("isTargetDay" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isTargetDay"] = false;
        }
        if (!("isExpired" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isExpired"] = false;
        }
        if (!("daysAfterTarget" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["daysAfterTarget"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Result}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result(/** @type {Partial<Result>} */($$parsedSource));
    }
}
