// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as countdown$0 from "./internal/countdown/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pet$0 from "./internal/pet/models.js";

export function AutostartAvailable(): $CancellablePromise<boolean> {
    return $Call.ByID(3316918190);
}

export function Countdown(target: string, includeToday: boolean, includeTarget: boolean, restWeekdays: number[] | null): $CancellablePromise<countdown$0.Result> {
    return $Call.ByID(3192200561, target, includeToday, includeTarget, restWeekdays);
}

export function GetConfig(): $CancellablePromise<config$0.Config> {
    return $Call.ByID(3902498144);
}

export function KeepInActivityArea(): $CancellablePromise<void> {
    return $Call.ByID(722066848);
}

export function RestoreHomePosition(): $CancellablePromise<void> {
    return $Call.ByID(539074676);
}

export function SaveConfig(v: config$0.Config): $CancellablePromise<void> {
    return $Call.ByID(2775748437, v);
}

export function SetCurrentPositionAsHome(): $CancellablePromise<void> {
    return $Call.ByID(3115897231);
}

export function SetMotionController(controller: pet$0.MotionController | null): $CancellablePromise<void> {
    return $Call.ByID(2010155752, controller);
}

export function StartJump(height: number, durationMS: number): $CancellablePromise<void> {
    return $Call.ByID(1371770762, height, durationMS);
}

export function StartMotion(direction: string, speed: number, durationMS: number): $CancellablePromise<void> {
    return $Call.ByID(3392516312, direction, speed, durationMS);
}

export function StopMotion(): $CancellablePromise<void> {
    return $Call.ByID(3578639128);
}
