// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as countdown$0 from "./internal/countdown/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pet$0 from "./internal/pet/models.js";

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function AutostartAvailable() {
    return $Call.ByID(3316918190);
}

/**
 * @param {string} target
 * @param {boolean} includeToday
 * @param {boolean} includeTarget
 * @param {number[]} restWeekdays
 * @returns {$CancellablePromise<countdown$0.Result>}
 */
export function Countdown(target, includeToday, includeTarget, restWeekdays) {
    return $Call.ByID(3192200561, target, includeToday, includeTarget, restWeekdays).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<config$0.Config>}
 */
export function GetConfig() {
    return $Call.ByID(3902498144).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function KeepInActivityArea() {
    return $Call.ByID(722066848);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RestoreHomePosition() {
    return $Call.ByID(539074676);
}

/**
 * @param {config$0.Config} v
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(v) {
    return $Call.ByID(2775748437, v);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SetCurrentPositionAsHome() {
    return $Call.ByID(3115897231);
}

/**
 * @param {pet$0.MotionController | null} controller
 * @returns {$CancellablePromise<void>}
 */
export function SetMotionController(controller) {
    return $Call.ByID(2010155752, controller);
}

/**
 * @param {number} height
 * @param {number} durationMS
 * @returns {$CancellablePromise<void>}
 */
export function StartJump(height, durationMS) {
    return $Call.ByID(1371770762, height, durationMS);
}

/**
 * @param {string} direction
 * @param {number} speed
 * @param {number} durationMS
 * @returns {$CancellablePromise<void>}
 */
export function StartMotion(direction, speed, durationMS) {
    return $Call.ByID(3392516312, direction, speed, durationMS);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopMotion() {
    return $Call.ByID(3578639128);
}

// Private type creation functions
const $$createType0 = countdown$0.Result.createFrom;
const $$createType1 = config$0.Config.createFrom;
