// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Result {
    "targetDate": string;
    "calendarDays": number;
    "workingDays": number;
    "isTargetDay": boolean;
    "isExpired": boolean;
    "daysAfterTarget": number;
}
